services:
  api_animal_adoption:
    build: .
    container_name: api_animal_adoption
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/animal_adoption
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123ateo9
      SPRING_PROFILES_ACTIVE: docker
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://keycloak.animal-adoption.com.br:8443/realms/ANIMAL_ADOPTION
    networks:
      - controlimage_network

networks:
  controlimage_network:
    external: true
