spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.animal-adoption.com.br:8443/realms/ANIMAL_ADOPTION
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/animal_adoption}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123ateo9}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    default-schema: animal_adoption
    validate-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${SCHEMA_NAME:animal_adoption}

  sql:
    init:
      mode: always
      encoding: UTF-8

server:
  port: 8081

image-api:
  url: http://localhost:8082
  url-images: http://localhost:8082
keycloak-config:
  client-public-key: ANIMAL_ADOPTION_CLIENT
  internal-url: https://keycloak.animal-adoption.com.br:8443