spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.barbershop-app.shop:8443/realms/ANIMAL_ADOPTION
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://72.61.38.221:5432/animal_adoption}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123ateo9}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${SCHEMA_NAME:animal_adoption}

  sql:
    init:
      mode: always
      encoding: UTF-8

server:
  port: 8081

image-api:
  url: http://image-api:8082
keycloak-config:
  client-public-key: ANIMAL_ADOPTION_CLIENT
  internal-url: https://keycloak:8443